 phrases = {'absolute_negatives'; 'aeroplane'; 'aeroplane_flying_in_sky'; ...
    'aeroplane_parked_at_airport'; 'bicycle'; 'bicycle_nextto_car'; 'bird'; ...
    'bird_flying_in_sky'; 'bottle'; 'car'; 'cat'; 'cat_lying_on_sofa'; ...
    'chair'; 'dog'; 'dog_jumping'; 'dog_lying_on_sofa'; 'dog_running'; ...
    'horse'; 'person'; 'person_drinking_bottle'; 'person_jumping'; ...
    'person_jumping_on_horse'; 'person_lying_in_beach'; 'person_lying_on_sofa'; ...
    'person_nextto_bicycle'; 'person_nextto_car'; 'person_nextto_horse'; ...
    'person_riding_bicycle'; 'person_riding_horse'; 'person_running'; ...
    'person_sitting_on_chair'; 'person_sitting_on_sofa'; 'sofa'};
cd G:\Documents\Visual_Phrases_Project
save('Phrases.mat', 'phrases');